# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "748b3c23523154b47eb65f66c5a21655"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Chatleaf"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
